name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.9'

      - name: Build
        run: gradle build
      - run: mv build/libs/stefansreleasedemogradle-0.0.1-SNAPSHOT.jar build/libs/stefansreleasedemogradle-1.${{ env.build-number }}.1.jar
      - run: mkdir staging && cp build/libs/stefansreleasedemogradle-1.${{ env.build-number }}.1.jar staging/stefansreleasedemogradle-1.${{ env.build-number }}.1.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Version"
          files: |
            staging/*.jar


