name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  build-number: ${{github.run_number}}

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: Hashcracker
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 30s

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.8'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -P 3306 --silent && echo "MySQL is ready!" && break
            echo "Waiting for MySQL... ($i/30)"
            sleep 5
          done

      - name: Build and run test
        run: gradle build
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          GHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
          GHUB_CLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}

      - name: Package the application
        run:  |
          mv build/libs/ITsec_individuell-0.0.1-SNAPSHOT.jar build/libs/ITsec_individuell-1.${{ env.build-number }}.1.jar
          mkdir staging
          cp build/libs/ITsec_individuell-1.${{ env.build-number }}.1.jar staging/ITsec_individuell-1.${{ env.build-number }}.1.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Version"
          files: |
            staging/*.jar


